In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df= pd.read_excel('/content/drive/MyDrive/ML_Project/owid-covid-data_with_latest_update_2.xlsx')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df.head(10)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,hospital_beds_per_thousand,life_expectancy,human_development_index,population
0,ZAF,Africa,South Africa,2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,...,12294.876,18.9,200.38,5.52,8.1,33.2,2.32,64.13,0.709,59893884
1,ZAF,Africa,South Africa,2020-01-06,0.0,0.0,0.0,0.0,0.0,0.0,...,12294.876,18.9,200.38,5.52,8.1,33.2,2.32,64.13,0.709,59893884
2,ZAF,Africa,South Africa,2020-01-07,0.0,0.0,0.0,0.0,0.0,0.0,...,12294.876,18.9,200.38,5.52,8.1,33.2,2.32,64.13,0.709,59893884
3,ZAF,Africa,South Africa,2020-01-08,0.0,0.0,0.0,0.0,0.0,0.0,...,12294.876,18.9,200.38,5.52,8.1,33.2,2.32,64.13,0.709,59893884
4,ZAF,Africa,South Africa,2020-01-09,0.0,0.0,0.0,0.0,0.0,0.0,...,12294.876,18.9,200.38,5.52,8.1,33.2,2.32,64.13,0.709,59893884
5,ZAF,Africa,South Africa,2020-01-10,0.0,0.0,0.0,0.0,0.0,0.0,...,12294.876,18.9,200.38,5.52,8.1,33.2,2.32,64.13,0.709,59893884
6,ZAF,Africa,South Africa,2020-01-11,0.0,0.0,0.0,0.0,0.0,0.0,...,12294.876,18.9,200.38,5.52,8.1,33.2,2.32,64.13,0.709,59893884
7,ZAF,Africa,South Africa,2020-01-12,0.0,0.0,0.0,0.0,0.0,0.0,...,12294.876,18.9,200.38,5.52,8.1,33.2,2.32,64.13,0.709,59893884
8,ZAF,Africa,South Africa,2020-01-13,0.0,0.0,0.0,0.0,0.0,0.0,...,12294.876,18.9,200.38,5.52,8.1,33.2,2.32,64.13,0.709,59893884
9,ZAF,Africa,South Africa,2020-01-14,0.0,0.0,0.0,0.0,0.0,0.0,...,12294.876,18.9,200.38,5.52,8.1,33.2,2.32,64.13,0.709,59893884

In [ ]:
#checking the first 10 elements
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 429435 entries, 0 to 429434
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    429435 non-null  object
 1   continent                                   402910 non-null  object
 2   location                                    429435 non-null  object
 3   date                                        429435 non-null  object
 4   total_cases                                 411804 non-null  float64
 5   new_cases                                   410159 non-null  float64
 6   new_cases_smoothed                          408929 non-null  float64
 7   total_deaths                                411804 non-null  float64
 8   new_deaths                                  410608 non-null  float64
 9   new_deaths_smoothed                         409378 non-null  float64
 10  total_cases_per_million                     411804 non-null  float64
 11  new_cases_per_million                       410159 non-null  float64
 12  new_cases_smoothed_per_million              408929 non-null  float64
 13  total_deaths_per_million                    411804 non-null  float64
 14  new_deaths_per_million                      410608 non-null  float64
 15  new_deaths_smoothed_per_million             409378 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                39116 non-null   float64
 18  icu_patients_per_million                    39116 non-null   float64
 19  hosp_patients                               40656 non-null   float64
 20  hosp_patients_per_million                   40656 non-null   float64
 21  weekly_icu_admissions                       10993 non-null   float64
 22  weekly_icu_admissions_per_million           10993 non-null   float64
 23  weekly_hosp_admissions                      24497 non-null   float64
 24  weekly_hosp_admissions_per_million          24497 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object
 34  total_vaccinations                          85417 non-null   float64
 35  people_vaccinated                           81132 non-null   float64
 36  people_fully_vaccinated                     78061 non-null   float64
 37  total_boosters                              53600 non-null   float64
 38  new_vaccinations                            70971 non-null   float64
 39  new_vaccinations_smoothed                   195029 non-null  float64
 40  total_vaccinations_per_hundred              85417 non-null   float64
 41  people_vaccinated_per_hundred               81132 non-null   float64
 42  people_fully_vaccinated_per_hundred         78061 non-null   float64
 43  total_boosters_per_hundred                  53600 non-null   float64
 44  new_vaccinations_smoothed_per_million       195029 non-null  float64
 45  new_people_vaccinated_smoothed              192177 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  192177 non-null  float64
 47  stringency_index                            196190 non-null  float64
 48  population_density                          360492 non-null  float64
 49  median_age                                  334663 non-null  float64
 50  aged_65_older                               323270 non-null  float64
 51  aged_70_older                               331315 non-null  float64
 52  gdp_per_capita                              328292 non-null  float64
 53  extreme_poverty                             211996 non-null  float64
 54  cardiovasc_death_rate                       328865 non-null  float64
 55  diabetes_prevalence                         345911 non-null  float64
 56  female_smokers                              247165 non-null  float64
 57  male_smokers                                243817 non-null  float64
 58  handwashing_facilities                      161741 non-null  float64
 59  hospital_beds_per_thousand                  290689 non-null  float64
 60  life_expectancy                             390299 non-null  float64
 61  human_development_index                     319127 non-null  float64
 62  population                                  429435 non-null  int64
 63  excess_mortality_cumulative_absolute        13411 non-null   float64
 64  excess_mortality_cumulative                 13411 non-null   float64
 65  excess_mortality                            13411 non-null   float64
 66  excess_mortality_cumulative_per_million     13411 non-null   float64
dtypes: float64(61), int64(1), object(5)
memory usage: 219.5+ MB

In [ ]:
#check missing data
df.isnull()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,hospital_beds_per_thousand,life_expectancy,human_development_index,population
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11734,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11735,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11736,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11737,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11738,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

iso_code                      0
continent                     0
location                      0
date                          0
total_cases                   6
                             ..
male_smokers                  0
hospital_beds_per_thousand    0
life_expectancy               0
human_development_index       0
population                    0
Length: 62, dtype: int64

In [ ]:
print(df.columns)

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

In [ ]:
df.shape

(429435, 67)

In [ ]:
df.isnull().mean()

iso_code                                   0.000000
continent                                  0.061767
location                                   0.000000
date                                       0.000000
total_cases                                0.041056
                                             ...
population                                 0.000000
excess_mortality_cumulative_absolute       0.968771
excess_mortality_cumulative                0.968771
excess_mortality                           0.968771
excess_mortality_cumulative_per_million    0.968771
Length: 67, dtype: float64

In [ ]:
num_cols_with_missing = df.isnull().any().sum()

In [ ]:
print(num_cols_with_missing)

63

In [ ]:
#checking the first 10 elements
df.info()

In [ ]:
#checking the first 10 elements
df.info()

In [ ]:
df['stringency_index'].isnull().sum()

In [ ]:
df[df['stringency_index'].isnull()]

In [ ]:
df['case'].isnull().mean() * 100

In [ ]:
#checking the first 10 elements
df.info()

In [ ]:
missing_percentage = df.isnull().mean() * 100

In [ ]:
print(missing_percentage)

In [ ]:
df['continent'].isnull().sum()

In [ ]:
df['continent'].isnull().mean() * 100

In [ ]:
df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,4.118040e+05,4.101590e+05,4.089290e+05,4.118040e+05,410608.000000,409378.000000,411804.000000,410159.000000,408929.000000,411804.000000,...,243817.000000,161741.000000,290689.000000,390299.000000,319127.000000,4.294350e+05,1.341100e+04,13411.000000,13411.000000,13411.000000
mean,7.365292e+06,8.017360e+03,8.041026e+03,8.125957e+04,71.852139,72.060873,112096.199396,122.357074,122.713844,835.514313,...,33.097723,50.649264,3.106912,73.702098,0.722139,1.520336e+08,5.604765e+04,9.766431,10.925353,1772.666400
std,4.477582e+07,2.296649e+05,8.661611e+04,4.411901e+05,1368.322990,513.636567,162240.412419,1508.778583,559.701638,1134.932671,...,13.853948,31.905375,2.549205,7.387914,0.148903,6.975408e+08,1.568691e+05,12.040658,24.560706,1991.892769
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.700000,1.188000,0.100000,53.280000,0.394000,4.700000e+01,-3.772610e+04,-44.230000,-95.920000,-2936.453100
25%,6.280750e+03,0.000000e+00,0.000000e+00,4.300000e+01,0.000000,0.000000,1916.100500,0.000000,0.000000,24.568000,...,22.600000,20.859000,1.300000,69.500000,0.602000,5.237980e+05,1.765000e+02,2.060000,-1.500000,116.872242
50%,6.365300e+04,0.000000e+00,1.200000e+01,7.990000e+02,0.000000,0.000000,29145.475000,0.000000,2.794000,295.089000,...,33.100000,49.542000,2.500000,75.050000,0.740000,6.336393e+06,6.815199e+03,8.130000,5.660000,1270.801400
75%,7.582720e+05,0.000000e+00,3.132860e+02,9.574000e+03,0.000000,3.143000,156770.190000,0.000000,56.253000,1283.817000,...,41.500000,82.502000,4.210000,79.460000,0.829000,3.296952e+07,3.912804e+04,15.160000,15.575000,2883.024150
max,7.758668e+08,4.423623e+07,6.319461e+06,7.057132e+06,103719.000000,14817.000000,763598.600000,241758.230000,34536.890000,6601.110000,...,78.100000,100.000000,13.800000,86.750000,0.957000,7.975105e+09,1.349776e+06,78.080000,378.220000,10293.515000

In [ ]:
df.describe(include='all')

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,429435,402910,429435,429435,4.118040e+05,4.101590e+05,4.089290e+05,4.118040e+05,410608.000000,409378.000000,...,243817.000000,161741.000000,290689.000000,390299.000000,319127.000000,4.294350e+05,1.341100e+04,13411.000000,13411.000000,13411.000000
unique,255,6,255,1688,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,OWID_HIC,Africa,High-income countries,2021-10-22,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,3026,95419,3026,261,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,7.365292e+06,8.017360e+03,8.041026e+03,8.125957e+04,71.852139,72.060873,...,33.097723,50.649264,3.106912,73.702098,0.722139,1.520336e+08,5.604765e+04,9.766431,10.925353,1772.666400
std,NaN,NaN,NaN,NaN,4.477582e+07,2.296649e+05,8.661611e+04,4.411901e+05,1368.322990,513.636567,...,13.853948,31.905375,2.549205,7.387914,0.148903,6.975408e+08,1.568691e+05,12.040658,24.560706,1991.892769
min,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,...,7.700000,1.188000,0.100000,53.280000,0.394000,4.700000e+01,-3.772610e+04,-44.230000,-95.920000,-2936.453100
25%,NaN,NaN,NaN,NaN,6.280750e+03,0.000000e+00,0.000000e+00,4.300000e+01,0.000000,0.000000,...,22.600000,20.859000,1.300000,69.500000,0.602000,5.237980e+05,1.765000e+02,2.060000,-1.500000,116.872242
50%,NaN,NaN,NaN,NaN,6.365300e+04,0.000000e+00,1.200000e+01,7.990000e+02,0.000000,0.000000,...,33.100000,49.542000,2.500000,75.050000,0.740000,6.336393e+06,6.815199e+03,8.130000,5.660000,1270.801400
75%,NaN,NaN,NaN,NaN,7.582720e+05,0.000000e+00,3.132860e+02,9.574000e+03,0.000000,3.143000,...,41.500000,82.502000,4.210000,79.460000,0.829000,3.296952e+07,3.912804e+04,15.160000,15.575000,2883.024150
max,NaN,NaN,NaN,NaN,7.758668e+08,4.423623e+07,6.319461e+06,7.057132e+06,103719.000000,14817.000000,...,78.100000,100.000000,13.800000,86.750000,0.957000,7.975105e+09,1.349776e+06,78.080000,378.220000,10293.515000

In [ ]:
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN

In [ ]:
#Drop columns with >90% missing values
high_missing_cols = [
    'icu_patients', 'icu_patients_per_million', 'hosp_patients', 'hosp_patients_per_million',
    'weekly_icu_admissions', 'weekly_icu_admissions_per_million',
    'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million',
    'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
    'excess_mortality', 'excess_mortality_cumulative_per_million'
]

In [ ]:

df.drop(columns=high_missing_cols, inplace=True)

In [ ]:
df.shape

(429435, 55)

In [ ]:
 #Fill missing values (low-missing columns <5%) using forward fill (good for time series)
low_missing_cols = [
    'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed',
    'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million',
    'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million'
]

df[low_missing_cols] = df[low_missing_cols].fillna(method='ffill')

/tmp/ipython-input-8-2658811149.py:8: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[low_missing_cols] = df[low_missing_cols].fillna(method='ffill')

In [ ]:
df.shape

(429435, 55)

In [ ]:
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772

In [ ]:
missing_counts = df.isna().groupby(df['location']).sum().sum(axis=1)

In [ ]:
print(df)

      iso_code      continent      location       date  total_cases  \
0          ZAF         Africa  South Africa 2020-01-05          0.0
1          ZAF         Africa  South Africa 2020-01-06          0.0
2          ZAF         Africa  South Africa 2020-01-07          0.0
3          ZAF         Africa  South Africa 2020-01-08          0.0
4          ZAF         Africa  South Africa 2020-01-09          0.0
...        ...            ...           ...        ...          ...
11734      CAN  North America        Canada 2024-07-31    4819017.0
11735      CAN  North America        Canada 2024-08-01    4819017.0
11736      CAN  North America        Canada 2024-08-02    4819017.0
11737      CAN  North America        Canada 2024-08-03    4819017.0
11738      CAN  North America        Canada 2024-08-04    4819055.0

       new_cases  new_cases_smoothed  total_deaths  new_deaths  \
0            0.0            0.000000           0.0         0.0
1            0.0            0.000000           0.0         0.0
2            0.0            0.000000           0.0         0.0
3            0.0            0.000000           0.0         0.0
4            0.0            0.000000           0.0         0.0
...          ...                 ...           ...         ...
11734        0.0           46.714286       55282.0         0.0
11735        0.0           46.714286       55282.0         0.0
11736        0.0           46.714286       55282.0         0.0
11737        0.0           46.714286       55282.0         0.0
11738       38.0            5.428571       55282.0         0.0

       new_deaths_smoothed  ...  gdp_per_capita  extreme_poverty  \
0                 0.000000  ...       12294.876             18.9
1                 0.000000  ...       12294.876             18.9
2                 0.000000  ...       12294.876             18.9
3                 0.000000  ...       12294.876             18.9
4                 0.000000  ...       12294.876             18.9
...                    ...  ...             ...              ...
11734             0.285714  ...       44017.591              0.5
11735             0.285714  ...       44017.591              0.5
11736             0.285714  ...       44017.591              0.5
11737             0.285714  ...       44017.591              0.5
11738             0.000000  ...       44017.591              0.5

       cardiovasc_death_rate  diabetes_prevalence  female_smokers  \
0                    200.380                 5.52             8.1
1                    200.380                 5.52             8.1
2                    200.380                 5.52             8.1
3                    200.380                 5.52             8.1
4                    200.380                 5.52             8.1
...                      ...                  ...             ...
11734                105.599                 7.37            12.0
11735                105.599                 7.37            12.0
11736                105.599                 7.37            12.0
11737                105.599                 7.37            12.0
11738                105.599                 7.37            12.0

       male_smokers  hospital_beds_per_thousand  life_expectancy  \
0              33.2                        2.32            64.13
1              33.2                        2.32            64.13
2              33.2                        2.32            64.13
3              33.2                        2.32            64.13
4              33.2                        2.32            64.13
...             ...                         ...              ...
11734          16.6                        2.50            82.43
11735          16.6                        2.50            82.43
11736          16.6                        2.50            82.43
11737          16.6                        2.50            82.43
11738          16.6                        2.50            82.43

       human_development_index  population
0                        0.709    59893884
1                        0.709    59893884
2                        0.709    59893884
3                        0.709    59893884
4                        0.709    59893884
...                        ...         ...
11734                    0.929    38454328
11735                    0.929    38454328
11736                    0.929    38454328
11737                    0.929    38454328
11738                    0.929    38454328

[11739 rows x 62 columns]

In [ ]:
missing_counts.sort_values()

location
Czechia         16526
Malaysia        17282
Italy           19136
Canada          23944
South Africa    25611
Chile           26970
Australia       30598
dtype: int64

In [ ]:
df_filtered = pd.read_excel('/content/drive/MyDrive/owid-covid-data_Filtered.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/owid-covid-data_Filtered.xlsx'

In [ ]:
df_filtered['date'] = pd.to_datetime(df_filtered['date'])
df_filtered = df_filtered.sort_values('date')

#Set Generation interval (e.g. 5 days)
tau = 5

#shift new cases by tau days to estimate Rt
df_filtered['shifted_cases']= df_filtered['new_cases'].shift(tau)

#Calculate Rt.
df_filtered['reproduction_rate'] = df_filtered['new_cases'] / df_filtered['shifted_cases']

df_filtered['reproduction_rate_smoothed'] = df_filtered['reproduction_rate'].rolling(window=7).mean()

#View the result
print(df_filtered[['date', 'new_cases', 'reproduction_rate', 'reproduction_rate_smoothed']].dropna())

NameError: name 'df_filtered' is not defined